title: joaorosa.io | João Rosa thougths
site: joaorosa.io | João Rosa thougths

author:
  twitter: joaoasrosa

url: https://www.joaorosa.io
baseurl: 

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  # projects:
  #   output: true
  #   permalink: /project/:slug
  # workshops:
  #   output: true
  #   permalink: /workshop/:slug
  speaking:
    output: true
    permalink: /speaking/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  # -
  #   scope:
  #     path: ""
  #     type: "projects"
  #   values:
  #     layout: "project"
  # -
  #   scope:
  #     path: ""
  #     type: "workshops"
  #   values:
  #     layout: "workshop"
  -
    scope:
      path: ""
      type: "speaking"
    values:
      layout: "speaking"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-analytics
  - jekyll-seo-tag

paginate: 6
paginate_path: "/blog/page:num/"

jekyll_analytics:
  GoogleAnalytics:          
    id: UA-163111697-1          
    anonymizeIp: false      

webmaster_verifications:
  bing: 1234
  alexa: 1234
  yandex: 3273a397f926cef8
  baidu: 1234