title: joaorosa.io | João Rosa thougths
site: joaorosa.io | João Rosa thougths

author:
  twitter: joaoasrosa

url: https://www.joaorosa.io
baseurl: 

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  workshops:
    output: true
    permalink: /workshop/:slug
  services:
    output: true
    permalink: /service/:slug
  speaking:
    output: true
    permalink: /speaking/:slug
  projects:
    output: true
    permalink: /project/:slug
  writing:
    output: true
    permalink: /writing/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "workshops"
    values:
      layout: "workshop"
  -
    scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  -
    scope:
      path: ""
      type: "speaking"
    values:
      layout: "speaking"
  -
    scope:
      path: ""
      type: "writing"
    values:
      layout: "writing"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

paginate: 6
paginate_path: "/blog/page:num/"  

webmaster_verifications:
  bing: 5BA0004617293DE5A880E58CCABED582
  yandex: 3273a397f926cef8