remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
